// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOqndwj_hmiMSgtARDWdkA6MgXwuDp6EU',
    appId: '1:479016766520:web:47ef7c5b56e22afa566acd',
    messagingSenderId: '479016766520',
    projectId: 'signsense-56cc9',
    authDomain: 'signsense-56cc9.firebaseapp.com',
    storageBucket: 'signsense-56cc9.appspot.com',
    measurementId: 'G-BPR9CFQB6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaKeVUTdtiGd2QLl2KMohYavq2YCTHBBs',
    appId: '1:479016766520:android:343a4c8d47691327566acd',
    messagingSenderId: '479016766520',
    projectId: 'signsense-56cc9',
    storageBucket: 'signsense-56cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5unR49j2DvAZLMgzPLhnRGTCilwZpwFs',
    appId: '1:479016766520:ios:c32fd471b2a59f98566acd',
    messagingSenderId: '479016766520',
    projectId: 'signsense-56cc9',
    storageBucket: 'signsense-56cc9.appspot.com',
    iosBundleId: 'com.example.signsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5unR49j2DvAZLMgzPLhnRGTCilwZpwFs',
    appId: '1:479016766520:ios:871e4865a6c477bc566acd',
    messagingSenderId: '479016766520',
    projectId: 'signsense-56cc9',
    storageBucket: 'signsense-56cc9.appspot.com',
    iosBundleId: 'com.example.signsense.RunnerTests',
  );
}
